replicas: 1
minimumMasterNodes: 1
resources:
  requests:
    memory: "2Gi"
  limits:
    memory: "2Gi"
volumeClaimTemplate:
  resources:
    requests:
      storage: 5Gi
secret:
  enabled: true
  password: "12345678"
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5